# aeb Makefile
#
# `aeb` itself is a thin bash trampoline that lazy-builds the Aether
# tools under tools/ on first use. This Makefile pre-builds those
# binaries and installs a copy of the runtime tree to $PREFIX/share/aeb,
# with a small wrapper at $PREFIX/bin/aeb that pins AEB_HOME at the
# installed copy (decoupling installs from the dev tree).

AETHER ?= ae
PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin
SHAREDIR ?= $(PREFIX)/share/aeb

TOOLS := tools/aeb-main tools/aeb-init tools/aeb-link tools/aeb-graph tools/affected-targets tools/gcheckout tools/gen-orchestrator tools/file-to-label
INSTALL_TOOLS := tools/aeb-main tools/aeb-init tools/aeb-link tools/aeb-graph tools/affected-targets tools/gcheckout

# --lib tools makes the shared `aeblabel` module (tools/aeblabel/
# module.ae) importable by the tools that consume it (aeb-link,
# gen-orchestrator, file-to-label). Harmless for tools that don't —
# a flat tools/*.ae file is not a `name/module.ae` module, so the
# extra search root never picks one up by accident.
AEFLAGS ?= --lib tools

# Source-content hash of the aeb tree — a stable identity surfaced by
# `aeb --version` (AEB_STAMP) and the stale-install check. `git
# ls-files` covers every tracked source under aeb/lib/tools and
# excludes the gitignored prebuilt binaries; `find` is the
# outside-a-checkout fallback. Content, not mtime: a revert restores
# the prior hash, identical sources always hash the same.
SRCHASH_CMD = { git ls-files aeb lib tools 2>/dev/null | grep . || find aeb lib tools -type f; } | LC_ALL=C sort | xargs sha256sum 2>/dev/null | sha256sum | cut -c1-12

.PHONY: all build install uninstall clean check-install

all: build

build: $(TOOLS)
	@if [ -f "$(SHAREDIR)/AEB_STAMP" ]; then \
	    dev=$$( $(SRCHASH_CMD) ); \
	    inst=$$(awk '$$1=="src"{print $$2}' "$(SHAREDIR)/AEB_STAMP"); \
	    [ "$$dev" = "$$inst" ] || echo "note: installed aeb at $(SHAREDIR) is stale vs this tree ($$inst -> $$dev) — run 'make install'"; \
	fi

# One pattern rule for every tool — each tools/<name> is built from
# tools/<name>.ae. Replaces six near-identical explicit rules.
tools/%: tools/%.ae
	$(AETHER) build $< -o $@ $(AEFLAGS)

# install — copy the runtime tree to $(SHAREDIR) and drop a wrapper
# at $(BINDIR)/aeb that pins AEB_HOME at the installed copy. The
# wrapper is regenerated each install so PREFIX changes are picked up.
install: $(INSTALL_TOOLS)
	@mkdir -p $(BINDIR) $(SHAREDIR)
	rm -f $(BINDIR)/aeb
	rm -rf $(SHAREDIR)/lib $(SHAREDIR)/tools
	cp -f aeb $(SHAREDIR)/aeb
	chmod +x $(SHAREDIR)/aeb
	cp -R lib $(SHAREDIR)/lib
	cp -R tools $(SHAREDIR)/tools
	@printf '%s\n' \
	    '#!/usr/bin/env bash' \
	    '# aeb wrapper — generated by aeb `make install`' \
	    'export AEB_HOME="$(SHAREDIR)"' \
	    'exec "$(SHAREDIR)/aeb" "$$@"' \
	    > $(BINDIR)/aeb
	chmod +x $(BINDIR)/aeb
	@SRCH=$$( $(SRCHASH_CMD) ); \
	 GITD=$$(git describe --always --dirty 2>/dev/null || echo unknown); \
	 printf 'src %s\ncommit %s\ninstalled %s\ntoolchain %s\n' \
	    "$$SRCH" "$$GITD" "$$(date '+%Y-%m-%d %H:%M:%S')" "$$($(AETHER) --version 2>/dev/null | head -1)" \
	    > $(SHAREDIR)/AEB_STAMP; \
	 echo "installed:"; \
	 echo "  wrapper:  $(BINDIR)/aeb"; \
	 echo "  runtime:  $(SHAREDIR)/"; \
	 echo "  version:  aeb 0.0.0-dev+$$SRCH (git $$GITD)"

uninstall:
	rm -f $(BINDIR)/aeb
	rm -rf $(SHAREDIR)

clean:
	rm -f $(TOOLS)

# check-install — is the installed aeb current with this source tree?
# Compares the dev tree's source-content hash against the installed
# AEB_STAMP. Catches the "accidentally running an older install"
# trap without any version-manager machinery.
check-install:
	@if [ ! -f "$(SHAREDIR)/AEB_STAMP" ]; then \
	    echo "aeb: not installed at $(SHAREDIR) — run 'make install'"; \
	else \
	    dev=$$( $(SRCHASH_CMD) ); \
	    inst=$$(awk '$$1=="src"{print $$2}' "$(SHAREDIR)/AEB_STAMP"); \
	    if [ "$$dev" = "$$inst" ]; then \
	        echo "aeb: installed tree is current (src $$inst)"; \
	    else \
	        echo "aeb: installed tree is STALE — installed src $$inst, this tree $$dev — run 'make install'"; \
	    fi; \
	fi
