# aeb Makefile
#
# `aeb` itself is a thin bash trampoline that lazy-builds the Aether
# tools under tools/ on first use. This Makefile pre-builds those
# binaries and installs a copy of the runtime tree to $PREFIX/share/aeb,
# with a small wrapper at $PREFIX/bin/aeb that pins AEB_HOME at the
# installed copy (decoupling installs from the dev tree).

AETHER ?= ae
PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin
SHAREDIR ?= $(PREFIX)/share/aeb

TOOLS := tools/aeb-main tools/aeb-init tools/aeb-link tools/aeb-graph tools/affected-targets tools/gcheckout tools/gen-orchestrator tools/file-to-label
INSTALL_TOOLS := tools/aeb-main tools/aeb-init tools/aeb-link tools/aeb-graph tools/affected-targets tools/gcheckout

# --lib tools makes the shared `aeblabel` module (tools/aeblabel/
# module.ae) importable by the tools that consume it (aeb-link,
# gen-orchestrator, file-to-label). Harmless for tools that don't —
# a flat tools/*.ae file is not a `name/module.ae` module, so the
# extra search root never picks one up by accident.
AEFLAGS ?= --lib tools

.PHONY: all build install uninstall clean

all: build

build: $(TOOLS)

# One pattern rule for every tool — each tools/<name> is built from
# tools/<name>.ae. Replaces six near-identical explicit rules.
tools/%: tools/%.ae
	$(AETHER) build $< -o $@ $(AEFLAGS)

# install — copy the runtime tree to $(SHAREDIR) and drop a wrapper
# at $(BINDIR)/aeb that pins AEB_HOME at the installed copy. The
# wrapper is regenerated each install so PREFIX changes are picked up.
install: $(INSTALL_TOOLS)
	@mkdir -p $(BINDIR) $(SHAREDIR)
	rm -f $(BINDIR)/aeb
	rm -rf $(SHAREDIR)/lib $(SHAREDIR)/tools
	cp -f aeb $(SHAREDIR)/aeb
	chmod +x $(SHAREDIR)/aeb
	cp -R lib $(SHAREDIR)/lib
	cp -R tools $(SHAREDIR)/tools
	@printf '%s\n' \
	    '#!/usr/bin/env bash' \
	    '# aeb wrapper — generated by aeb `make install`' \
	    'export AEB_HOME="$(SHAREDIR)"' \
	    'exec "$(SHAREDIR)/aeb" "$$@"' \
	    > $(BINDIR)/aeb
	chmod +x $(BINDIR)/aeb
	@echo "installed:"
	@echo "  wrapper:  $(BINDIR)/aeb"
	@echo "  runtime:  $(SHAREDIR)/"

uninstall:
	rm -f $(BINDIR)/aeb
	rm -rf $(SHAREDIR)

clean:
	rm -f $(TOOLS)
