# aetherBuild Makefile
#
# `aeb` itself is a thin bash trampoline that lazy-builds the Aether
# tools under tools/ on first use. This Makefile pre-builds those
# binaries and installs a copy of the runtime tree to $PREFIX/share/aeb,
# with a small wrapper at $PREFIX/bin/aeb that pins AEB_HOME at the
# installed copy (decoupling installs from the dev tree).

AETHER ?= ae
PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin
SHAREDIR ?= $(PREFIX)/share/aeb

TOOLS := tools/aeb-main tools/aeb-init tools/aeb-link tools/aeb-graph tools/affected-targets tools/gcheckout
# tools/gcheckout currently fails to link against the Aether stdlib
# (extern symbols not pulled in); the trampoline will lazy-build it
# at first use. Install only requires the tools that build cleanly.
INSTALL_TOOLS := tools/aeb-main tools/aeb-init tools/aeb-link tools/aeb-graph tools/affected-targets

.PHONY: all build install uninstall clean

all: build

build: $(TOOLS)

tools/aeb-main: tools/aeb-main.ae
	$(AETHER) build $< -o $@

tools/aeb-init: tools/aeb-init.ae
	$(AETHER) build $< -o $@

tools/aeb-link: tools/aeb-link.ae
	$(AETHER) build $< -o $@

tools/aeb-graph: tools/aeb-graph.ae
	$(AETHER) build $< -o $@

tools/affected-targets: tools/affected-targets.ae
	$(AETHER) build $< -o $@

tools/gcheckout: tools/gcheckout.ae
	$(AETHER) build $< -o $@

# install — copy the runtime tree to $(SHAREDIR) and drop a wrapper
# at $(BINDIR)/aeb that pins AEB_HOME at the installed copy. The
# wrapper is regenerated each install so PREFIX changes are picked up.
install: $(INSTALL_TOOLS)
	@mkdir -p $(BINDIR) $(SHAREDIR)
	rm -f $(BINDIR)/aeb
	rm -rf $(SHAREDIR)/lib $(SHAREDIR)/tools
	cp -f aeb $(SHAREDIR)/aeb
	chmod +x $(SHAREDIR)/aeb
	cp -R lib $(SHAREDIR)/lib
	cp -R tools $(SHAREDIR)/tools
	@printf '%s\n' \
	    '#!/usr/bin/env bash' \
	    '# aeb wrapper — generated by aetherBuild `make install`' \
	    'export AEB_HOME="$(SHAREDIR)"' \
	    'exec "$(SHAREDIR)/aeb" "$$@"' \
	    > $(BINDIR)/aeb
	chmod +x $(BINDIR)/aeb
	@echo "installed:"
	@echo "  wrapper:  $(BINDIR)/aeb"
	@echo "  runtime:  $(SHAREDIR)/"

uninstall:
	rm -f $(BINDIR)/aeb
	rm -rf $(SHAREDIR)

clean:
	rm -f $(TOOLS)
